apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # *Se codifican en base64 los valores de las variables de entorno
  
  # PG_USER_EMAIL: admin@gmail.com
  PG_USER_EMAIL: YWRtaW5AZ21haWwuY29t

  # DB_PASSWORD: Admin123
  DB_PASSWORD: QWRtaW4xMjM=