apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # *Se codifican en base64 los valores de las variables de entorno
  
  # DB_USER: postgres
  DB_USER: cG9zdGdyZXM=

  # DB_PASSWORD: Admin123
  DB_PASSWORD: QWRtaW4xMjM=