apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # *Se codifican en base64 los valores de las variables de entorno
  
  # JWT_SECRET: Admin123
  JWT_SECRET: QWRtaW4xMjM=