apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin 
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pg-admin-secrets
              key: PG_USER_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-admin-secrets
              key: DB_PASSWORD
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pg-admin-storage
      volumes:
      - name: pg-admin-storage
        persistentVolumeClaim:
          claimName: pg-admin-pvc
---
# *Service definition

apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  type: NodePort # Nos permite acceder a la aplicación desde el navegador
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80 # Cualquier puerto
      targetPort: 80
      nodePort: 30200 # Puerto de acceso (rango: 30000 - 32767)