apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-admin-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pg-admin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi