apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_NAME: postgres
  # En el DB_HOST se pone el nombre del servicio de la base de datos
  DB_HOST: postgres-service
  DB_PORT: "5432"